######################################################################
# Automatically generated by qmake (3.0) Tue May 23 19:19:07 2017
######################################################################

QT += core
TEMPLATE = app
TARGET = qt_indt_test
INCLUDEPATH += . headers

CONFIG += qt c++11

QT += core gui widgets

# Input
HEADERS += headers/MainWindow.h headers/treeitem.h headers/treemodel.h
SOURCES += sources/main.cpp \
           sources/MainWindow.cpp \
           sources/treeitem.cpp \
           sources/treemodel.cpp \
           tests/TestQString.cpp
